Repository the-white-sox/css-parser, pull requests merged in 2022-12, with the labels that each got.

#11 fix: tweak urls
  src/parser.rs
  src/parser/url.rs
Labels: bug, enhancement

#25 Feat: adding basic selectors and tests to the project
  src/parser.rs
  src/parser/basic_selector.rs
Labels: enhancement

#18 docs: add note to grammar about case
  GRAMMAR.md
Labels: documentation

#9 feat: introduce parsing for lengths
  src/parser.rs
  src/parser/length.rs
  src/parser/length/tests.rs
  src/parser/length_or_percentage.rs
  src/parser/media_query/media_feature.rs
  src/parser/percentage.rs
  src/parser/rule/ruleset.rs
  src/parser/side.rs
  test_files/good/media_rules.css
Labels: enhancement

#16 refactor: use new style for mediatype
  src/parser/media_query/media_type.rs
Labels: enhancement

#24 feat: parse declaration
  src/parser.rs
  src/parser/color.rs
  src/parser/declaration.rs
  src/parser/declaration/text_align.rs
  src/parser/declaration/vec.rs
  src/parser/media_query/media_feature.rs
Labels: enhancement

#34 feat: add support for `color` declaration
  src/parser/declaration.rs
Labels: enhancement

#36 feat: parse selectors
  GRAMMAR.md
  src/parser.rs
  src/parser/basic_selector.rs
  src/parser/rule/ruleset.rs
  src/parser/selector.rs
  src/parser/selector/attribute_selector.rs
  src/parser/selector/combinator.rs
  src/parser/selector/pseudo_class.rs
  test_files/good/selectors.css
Labels: enhancement

#39 refactor!: change some decls value type
  src/parser/declaration.rs
Labels: bug

#40 feat: add support for `ch` unit
  GRAMMAR.md
  src/parser/length.rs
  src/parser/length/tests.rs
Labels: enhancement
